"""`decoy init` -- interactive scaffolder for a starter pipeline YAML.

The only place wizards belong (CLI_UX_GUIDE.md section 13). Walks the user
through 4-5 prompts and writes a starter `pipeline.yaml` they can iterate on.
"""

from __future__ import annotations

from pathlib import Path

import typer

from decoy.ui.output import OutputMode, emit_json, setup_output
from decoy.ui.theme import accent, code, error, hint, success


_INIT_EPILOG = """\
Examples:

  decoy init
    Interactive Q&A; writes pipeline.yaml in the current directory.

  decoy init --out my_pipeline.yaml
    Choose the output filename.

  decoy init --yes
    Skip confirmation when overwriting an existing file.

See also: decoy validate, decoy run.
"""


_TEMPLATE = """\
# Generated by `decoy init` -- edit freely.
version: '1.0'

global_settings:
  seed: 42

input:
  type: csv
  path: '{input_path}'
  csv_options:
    delimiter: ','
    encoding: utf-8

output:
  type: csv
  path: '{output_path}'
  csv_options:
    delimiter: ','
    encoding: utf-8

mappings:
  store_directory: 'mappings'

logging:
  level: info
  file: 'decoy_run.log'

masking_rules:
{rules}
"""


_RULE_PRESETS: dict[str, list[tuple[str, str, dict]]] = {
    "minimal": [
        ("name", "faker", {"faker_type": "name"}),
        ("email", "faker", {"faker_type": "email"}),
        ("ssn", "hash", {"algorithm": "sha256"}),
    ],
    "hipaa": [
        ("first_name", "faker", {"faker_type": "first_name"}),
        ("last_name", "faker", {"faker_type": "last_name"}),
        ("email", "faker", {"faker_type": "email"}),
        ("phone", "faker", {"faker_type": "phone_number"}),
        ("ssn", "hash", {"algorithm": "sha256"}),
        ("dob", "date_shift", {"jitter_days": 30}),
        ("zip", "redact", {"keep_chars": 3}),
    ],
}


def _format_rule(column: str, mask: str, params: dict) -> str:
    lines = [f"  - column: {column}", f"    type: {mask}"]
    for k, v in params.items():
        lines.append(f"    {k}: {v}")
    return "\n".join(lines)


def _init(
    out: Path = typer.Option(
        Path("pipeline.yaml"),
        "--out",
        help="Where to write the pipeline YAML.",
    ),
    yes: bool = typer.Option(
        False,
        "--yes",
        "-y",
        help="Skip overwrite confirmation.",
    ),
    json_: bool = typer.Option(
        False, "--json", help="Skip the wizard; emit a JSON record of what was written."
    ),
    quiet: bool = typer.Option(
        False, "--quiet", "-q", help="Suppress stdout. Errors still go to stderr."
    ),
    verbose: bool = typer.Option(
        False, "--verbose", "-v", help="Enable debug-level CLI logs on stderr."
    ),
) -> None:
    """Scaffold a starter pipeline YAML through a short Q&A.

    Use this on a fresh project to get a working pipeline you can run end to
    end, then edit the rules and paths to match your data. The wizard is the
    only interactive prompt in the CLI -- every other command is one-shot.
    """
    state = setup_output(json_, quiet, verbose)

    if out.exists() and not yes:
        if state.mode is not OutputMode.default:
            state.err_console.print(error("error:"), f"{out} already exists.")
            state.err_console.print(" ", hint("hint:"), "rerun with --yes to overwrite.")
            raise typer.Exit(code=1)
        size = out.stat().st_size
        state.console.print(
            f"This will overwrite {out} ({size} bytes). Continue?",
        )
        if not typer.confirm("Overwrite?", default=False):
            state.console.print(hint("aborted."))
            raise typer.Exit(code=1)

    if state.mode is OutputMode.json:
        # Non-interactive: produce a minimal scaffold with the default preset.
        rules = _RULE_PRESETS["minimal"]
        rendered = _TEMPLATE.format(
            input_path="data/input.csv",
            output_path="data/masked.csv",
            rules="\n".join(_format_rule(*r) for r in rules),
        )
        out.write_text(rendered, encoding="utf-8")
        emit_json(
            state,
            {
                "command": "init",
                "status": "ok",
                "out": str(out),
                "preset": "minimal",
                "rule_count": len(rules),
            },
        )
        return

    if state.mode is OutputMode.quiet:
        # Same minimal scaffold, no prompts, no output.
        rules = _RULE_PRESETS["minimal"]
        rendered = _TEMPLATE.format(
            input_path="data/input.csv",
            output_path="data/masked.csv",
            rules="\n".join(_format_rule(*r) for r in rules),
        )
        out.write_text(rendered, encoding="utf-8")
        return

    # Interactive Q&A.
    state.console.print(accent("decoy init"), "-- starter pipeline scaffold")
    state.console.print(hint("press Enter to accept the default in [brackets]."))
    state.console.print()

    input_path = typer.prompt("Input CSV path", default="data/input.csv")
    output_path = typer.prompt("Output CSV path", default="data/masked.csv")
    preset = typer.prompt(
        "Rule preset (minimal | hipaa)",
        default="minimal",
    ).strip().lower()
    while preset not in _RULE_PRESETS:
        state.console.print(error("error:"), f"unknown preset {preset!r}.")
        state.console.print(" ", hint("hint:"), "pick one of: minimal, hipaa.")
        preset = typer.prompt("Rule preset", default="minimal").strip().lower()

    rules = _RULE_PRESETS[preset]
    rendered = _TEMPLATE.format(
        input_path=input_path,
        output_path=output_path,
        rules="\n".join(_format_rule(*r) for r in rules),
    )
    out.write_text(rendered, encoding="utf-8")

    state.console.print()
    state.console.print(success("OK"), "wrote", code(str(out)))
    state.console.print(hint("Next:"), code(f"decoy validate {out}"))


_init.__doc__ = _init.__doc__

INIT_EPILOG = _INIT_EPILOG


def init_command():  # exported for __main__
    return _init
