version: 1
global_settings:
  seed: 42
sources:
  customers:
    type: file
    format: csv
    path: test_demo_dir\customers.csv
tables:
- name: customers
  columns:
  - name: customer_id
    strategy: redact
  - name: first_name
    strategy: faker
    provider: person_first_name
  - name: last_name
    strategy: faker
    provider: person_last_name
  - name: email
    strategy: faker
    provider: person_email
  - name: ssn
    strategy: redact
  - name: dob
    strategy: redact
  - name: zip
    strategy: redact
  - name: gender
    strategy: passthrough
targets:
  customers:
    type: file
    format: csv
    path: test_demo_dir\customers_masked.csv
